version: 1
interfaces:
  - metaData:
      protocolId: 1
      description: "DEYE SUN-5/6/8/10/12K-SG04LP3"
    connection:
      baudRate: 9600
      parity: EVEN
      dataBits: 8
      stopBits: 1
    mapping:
      power:
        register:
          - 672
          - 673
        unit: KW
        type: "power"
        fc: READ_HOLDING_REGISTERS
      powerReduction:
        register:
          - 40
        unit: PERCENT
        type: "powerReduction"
        fc: WRITE_SINGLE_REGISTER
  - metaData:
      protocolId: 1
      description: "ReFuSol"
    connection:
      baudRate: 9600
      parity: EVEN
      dataBits: 8
      stopBits: 1
    mapping:
      power:
        register:
          - 672
          - 673
        unit: KW
        type: "power"
        fc: READ_HOLDING_REGISTERS
      powerReduction:
        register:
          - 40
        unit: PERCENT
        type: "powerReduction"
        fc: WRITE_SINGLE_REGISTER
