version: 1
interfaces:
  - metaData:
      manufacturer:
        manufacturerId: 1
        manufacturer: "DEYE"
    devices:
      - deviceId: 1
        deviceType: HYBRID_INVERTER
        name: "DEYE SUN-5K-SG04LP3"
        connection:
          baudRate: 9600
          parity: EVEN
          dataBits: 8
          stopBits: 1
        mapping:
          power:
            register:
              - 672
              - 673
            unit: KW
            type: "power"
            fc: READ_HOLDING_REGISTERS
          powerReduction:
            register:
              - 40
            unit: PERCENT
            type: "powerReduction"
            fc: WRITE_SINGLE_REGISTER
      - deviceId: 2
        deviceType: HYBRID_INVERTER
        name: "DEYE SUN-6K-SG04LP3"
        connection:
          baudRate: 9600
          parity: EVEN
          dataBits: 8
          stopBits: 1
        mapping:
          power:
            register:
              - 672
              - 673
            unit: KW
            type: "power"
            fc: READ_HOLDING_REGISTERS
          powerReduction:
            register:
              - 40
            unit: PERCENT
            type: "powerReduction"
            fc: WRITE_SINGLE_REGISTER
      - deviceId: 3
        deviceType: HYBRID_INVERTER
        name: "DEYE SUN-8K-SG04LP3"
        connection:
          baudRate: 9600
          parity: EVEN
          dataBits: 8
          stopBits: 1
        mapping:
          power:
            register:
              - 672
              - 673
            unit: KW
            type: "power"
            fc: READ_HOLDING_REGISTERS
          powerReduction:
            register:
              - 40
            unit: PERCENT
            type: "powerReduction"
            fc: WRITE_SINGLE_REGISTER
      - deviceId: 4
        deviceType: HYBRID_INVERTER
        name: "DEYE SUN-10K-SG04LP3"
        connection:
          baudRate: 9600
          parity: EVEN
          dataBits: 8
          stopBits: 1
        mapping:
          power:
            register:
              - 672
              - 673
            unit: KW
            type: "power"
            fc: READ_HOLDING_REGISTERS
          powerReduction:
            register:
              - 40
            unit: PERCENT
            type: "powerReduction"
            fc: WRITE_SINGLE_REGISTER
      - deviceId: 5
        deviceType: HYBRID_INVERTER
        name: "DEYE SUN-12K-SG04LP3"
        connection:
          baudRate: 9600
          parity: EVEN
          dataBits: 8
          stopBits: 1
        mapping:
          power:
            register:
              - 672
              - 673
            unit: KW
            type: "power"
            fc: READ_HOLDING_REGISTERS
          powerReduction:
            register:
              - 40
            unit: PERCENT
            type: "powerReduction"
            fc: WRITE_SINGLE_REGISTER