version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: energycontrol
    restart: always
    environment:
      - POSTGRES_USER=energycontrol
      - POSTGRES_PASSWORD=Start1234*
      - POSTGRES_DATABASE=energycontrol
    ports:
      - '5432:5432'