version: '3.8'
services:
  ########################
  # Frontend
  ########################
  frontend-app:
    image: mamotec/energycontrol-frontend:main
    container_name: frontend-app
    restart: always
    ports:
      - '4200:80'
    links:
      - backend-app

  ########################
  # Backend
  ########################
  backend-app:
    image: mamotec/energycontrol-backend:main
    container_name: backend-app
    restart: always
    ports:
      - '8080:8080'
    environment:
      - DB_SERVER=database
    links:
      - database
      - influx
    volumes:
      #- /home/mamotec/docker/application.properties:/BOOT-INF/classes/application.properties
      - /Users/moritzv/IdeaProjects/energycontrol-backend/src/main/resources/application.properties:/BOOT-INF/classes/application.properties

  ########################
  # Datenbank
  ########################
  database:
    image: postgres:latest
    container_name: backend-db
    restart: always
    environment:
      - POSTGRES_USER=energycontrol
      - POSTGRES_PASSWORD=Start1234*
      - POSTGRES_DATABASE=energycontrol
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend-network

  ########################
  # Influx-DB
  ########################
  influx:
    image: influxdb:2.0
    container_name: influx
    restart: always
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=energycontrol
      - DOCKER_INFLUXDB_INIT_BUCKET=energycontrol
    volumes:
      - influxdata:/var/lib/influxdb
    networks:
      - backend-network

volumes:
  dbdata:
  influxdata:

networks:
  backend-network:
