version: '3.8'
services:
  frontend-app:
    image: mamotec/energycontrol-frontend
    container_name: frontend-app
    restart: always
    ports:
      - '4200:80'
    links:
      - backend-app

  backend-app:
    image: mamotec/energycontrol-backend
    container_name: backend-app
    restart: always
    ports:
      - '8080:8080'
    environment:
      - DB_SERVER=database
    links:
      - database

  database:
    image: postgres:latest
    container_name: backend-db
    restart: always
    environment:
      - POSTGRES_USER=energycontrol
      - POSTGRES_PASSWORD=Start1234*
      - POSTGRES_DATABASE=energycontrol
