version: '3.8'
services:
  ########################
  # Frontend
  ########################
  frontend-app:
    image: mamotec/energycontrol-frontend
    container_name: frontend-app
    restart: always
    ports:
      - '4200:80'
    links:
      - backend-app

  ########################
  # Backend
  ########################
  backend-app:
    image: mamotec/energycontrol-backend
    container_name: backend-app
    restart: always
    ports:
      - '8080:8080'
    environment:
      - DB_SERVER=database
    links:
      - database

  ########################
  # Datenbank
  ########################
  database:
    image: postgres:latest
    container_name: backend-db
    restart: always
    environment:
      - POSTGRES_USER=energycontrol
      - POSTGRES_PASSWORD=Start1234*
      - POSTGRES_DATABASE=energycontrol
    volumes:
      - dbdata:/var/lib/postgresql/data

  ########################
  # Node-red
  ########################
  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: always
    ports:
      - '1880:1880'
    volumes:
      - nodereddata:/data

volumes:
  dbdata:
  nodereddata: