services:
  ########################
  # Frontend
  ########################
  frontend-app:
    image: mamotec/energycontrol-frontend:main
    container_name: frontend-app
    ports:
      - '4200:80'
    depends_on:
      - backend-app

  ########################
  # Backend
  ########################
  backend-app:
    image: mamotec/energycontrol-backend:main
    container_name: backend-app
    ports:
      - '8080:8080'
      - '8887:8887'
    environment:
      - DB_SERVER=database
    depends_on:
      - database
      - influx
    volumes:
      - /home/mamotec/docker/application.properties:/app/application.properties
    networks:
      - backend-net

  ########################
  # Datenbank
  ########################
  database:
    image: postgres:latest
    container_name: backend-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=energycontrol
      - POSTGRES_PASSWORD=Start1234*
      - POSTGRES_DATABASE=energycontrol
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend-net


  ########################
  # Influx-DB
  ########################
  influx:
    image: arm64v8/influxdb
    container_name: influx
    ports:
      - '8086:8086'
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=energycontrol
      - DOCKER_INFLUXDB_INIT_BUCKET=energycontrol
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=QJwlnjiP8cOl3nB1O4E84SKC_9_66Zy6378cRUba1fBHVlAsl9368qReFVhD9m-NSaN8GZ2uIl-zxquLwWnzvQ==
    volumes:
      - influxdata:/var/lib/influxdb
    networks:
      - backend-net

volumes:
  dbdata:
  influxdata:
networks:
  backend-net: